---
title: "Nana  Boateng's Resume"
author: Nana Boateng
date: "`r Sys.Date()`"
knit: pagedown::chrome_print
output:
  pagedown::html_resume:
  
    css: ['css/resume_styles.css', 'resume']
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: true
---



Aside
================================================================================

Contact {#contact}
--------------------------------------------------------------------------------


- <i class="fa fa-envelope"></i> unltd148@yahoo.co.uk
- <i class="fa fa-link"></i> [restanalytics.com/](http://restanalytics.com/)
- <i class="fa fa-github"></i>[github](https://github.com/NanaAkwasiAbayieBoateng)
- <i class="fa fa-phone"></i> (901) 246-7618
- <i class="fa fa-linkedin"></i> [linkedin](https://www.linkedin.com/in/nana-boateng-26b9a226/)



Skills {#skills}
--------------------------------------------------------------------------------

- <i class="fa fa-laptop"></i> **Programming**: Python, R,SQL, Scala, Spark,
Matlab, SAS,Octave.
- <i class="fas fa-cloud"></i> **Cloud Computing**: AWS sagemaker, 
Microsoft Azure, Google cloud, Databricks.

- <i class="fa fa-laptop"></i> **Other software tools**: Stata, Minitab, Tableau, Power BI, Github/Bitbucket, SPSS, Linux/Unix, Docker.

- <i class="fa fa-laptop"></i> **Libraries**: PySpark, Sparklyr, Tensorflow/Keras, pyTorch,Scikit-learn,tidyverse, plotly,  ggplot2, tidymodels, H2O, Caret, Numpy, Matplotlib, Seaborn, Pandas, tidyverse,Spark ML, Elephas, Dist-Keras, Horovod.


Credentials
--------------------------------------------------------------------------------

- <i class="fa fa-drivers-license"></i> SQL and Relational Databases – IBM ,2021
- <i class="fa fa-drivers-license"></i> Professional Educator License (IL): Docker Essentials – A developer Introduction, IBM, 2020
- <i class="fa fa-drivers-license"></i> Data Science with Scala - IBM, 2020
- <i class="fa fa-drivers-license"></i> Certified Base Programmer – SAS



Main
================================================================================

Nana Boateng {#title}
--------------------------------------------------------------------------------
Nana Boateng is a Data Scientist with professional experience in machine learning, Deep learning, computer vision, natural language processing, optimization techniques, predictive analytics, statistical analysis and spatial data visualization.

Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------
### University Of Memphis

PhD.

Memphis, TN

2016

Applied Statistics

### University Of Memphis
M.S.

Memphis, TN

2014

Applied Statistics

### University Of Memphis
M.A.

Memphis, TN

2017

Economics



### Middle Tennessee State University
M.S.

Murfreesboro,TN

2012

Mathematics


### Institute of Commercial Managers, United Kingdom
Graduate Diploma

Kumasi, Ghana

2010

Business Studies


### Kwame Nkrumah University of Science and Technology
B.S.

Kumasi, Ghana

2007

Mathematics


Professional Experience {data-icon=key}
--------------------------------------------------------------------------------

### NICE Systems Inc.

Data Scientist

Alpharetta, GA

2019 - To present



- Build machine learning models for financial fraud detection.
- Perform analysis to support the deployment of fraud prevention analytical models.
- Analyze fraud cases obtained from clients.
- Research data patterns in order to find patterns predictive of fraud.
- Improve the quality and actual implementation of computational algorithms and tools.
- Optimize the detection performance of NICE Actimize Fraud products and improve customers’ experience with our Fraud solutions.
- Define product requirements for analytics and provide feedback to the product team on ways in which product may be improved.
- Develop and enhance our solution-specific risk scores.
- Measure the quality of the analytical performance of Fraud Products.
- Develop tools to support model tuning, performance tracking and automation.
- Develop custom detection logic for specific clients.



### Catalina Marketing Corporation

Senior Data Scientist

Atlanta, GA

2018 - 2019

- Built recommender systems for CVC/SharebuildR campaigns with Matrix factorization methods such as ALS and Embedding with tools such as Spark and Keras. Explored Distributed Learning tools such as Elephas, Dist-Keras and Horovod Runner.
- Built an end –to-end flow model to rank propensity and redemption forecast models with tools such as Scikit-learn, Spark.
- Build visualizations and dashboard using shiny to display forecast from a revenue management-forecasting model.
- Mentoring Associate Data Scientist.




### Fiat Chrysler Automobiles

Data Scientist

Auburn-Hills, MI

2017 - 2018

- Pothole and significant events detection with machine learning. Used Machine learning models including MLP, XGBoost and AutoML to detect and to predict pothole size.
-  Lead manpower requirements project to predict with better accuracy the number of vehicles that would be sent to Chrysler Proving Grounds for vehicle testing. This allowed the manpower team to hire the right number of drivers thereby reducing cost otherwise incurred from hiring more drivers than will be needed.
- Sentiment Analysis of FCA employee and ex-employee reviews: Scraped and analyzed thousands of employee and ex-employees reviews from Glassdoor and Indeed between 2008 and 2018.
- Lead on multiple analytical projects using Customer Usage Data (CUDA) and warranty data to drive insights into customer mileage, identify warranty concerns and improve overall durability of FCA vehicles.
- Lead Trailer Tow project using data from Control Tec database to analyze 95th Percentile trailer towing FCA SUV vehicles.
- Member of team developing Qlikview interface to various FCA vehicle databases Participated in weekly meetings to analyze various stages of the development Qlikview.


### Baptist Memorial Hospital

Data  Analyst/ Manager

Memphis, TN

2016 - 2017

- Responsible for data management that includes data collection and database management for the Thoracic Oncology Multidisciplinary Clinic.
- Duties include collecting data at conferences and during clinics and reporting to Medical Director, Medical Steering Committee, Administration and various grant-funding organizations as directed.
- Perform a prospective matched cohort comparative effectiveness study of patients receiving serial versus multidisciplinary care, with key patient-centered endpoints (survival, satisfaction with the care experience, timeliness and appropriateness of care, quality of staging).
- Perform statistical analysis to determine the quality of care and survival between multidisciplinary program and serial care program using models such as conditional fixed effects logistic regression for binary categorical outcomes; fixed effects generalized linear models and fixed effects proportional hazard model for survival analysis.



### St. Jude Children’s Research Hospital,

Graduate Research Assistant

Memphis, TN

2014 - 2015

- Gastronomy complications in pediatric cancer patients.
- The effect of dynamic contrast: enhanced MRI(DEMRI) on tumor angiogenic activity and in predicting tumor response of OS2008 patients.
- Evaluation of alternative in vivo screening methodology: Analysis of single mouse tumor response results from PPTP.
- The significance of splenomegaly at diagnosis in pediatric Hodgkin lymphoma.


Teaching Experience {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------
### Georgia Gwinnett College

Part -Time Faculty of Mathematics

Lawrenceville, GA

2020 - 2021

- Instructor for mathematics and statistics.

### Baptist College of Health Sciences

Adjunct Instructor

Memphis, TN

2015 - 2016


- Instructor for mathematics and statistics.



### The University of Memphis

Graduate Teaching Assistant

Memphis, TN

2012 - 2016


- Taught Introduction to Statistics, Foundations of Math, and Elementary Calculus.

### Middle Tennessee State University

Graduate Teaching Assistant 

Murfreesboro, TN

2010 - 2012

- Primary Instructor for College Algebra and Trigonometry




Selected Peer-reviewed Publications {data-icon=flask}
--------------------------------------------------------------------------------
### Contextual Text Embeddings for Twi.

Paul Azunre, Salomey Osei, Salomey Addo, Lawrence Asamoah Adu-Gyamfi, Stephen Moore, Bernard Adabankah, Bernard Opoku, Clara Asare-Nyarko, Samuel Nyarko, Cynthia Amoaba, Esther Dansoa Appiah, Felix Akwerh, Richard Nii Lante Lawson, Joel Budu, Emmanuel Debrah, **Nana Boateng**, Wisdom Ofori, Edwin Buabeng-Munkoh, Franklin Adjei, Isaac Kojo Essel Ampomah, Joseph Otoo, Reindorf Borkor, Standylove Birago Mensah, Lucien Mensah, Mark Amoako Marcel, Anokye Acheampong Amponsah, James Ben Hayfron-Acquah.


Atlanta, GA

 2021

### Multidisciplinary care and the use of treatment modalities for non–small cell lung cancer (NSCLC) in a large community healthcare setting
M. Ray, N. Faris, F. Rugless, M. Smeltzer, C Foust, B. Jackson, **N. Boateng**
International Journal of Radiation Oncology• Biology• Physics 98 (1), 226.

Memphis, TN

2017

### Evaluation of Alternative In Vivo Drug Screening Methodology: single mouse analysis: A Retrospective Single-Institution Review, Cancer Research.

Brendan Murphy, Han Yin, John Maris, E Kolb, Richard Gorlick, C. Patrick Reynolds, Min Kang, Stephen Keir, Raushan Kurmasheva, Igor Dvorchik, Jianrong Wu, Catherine Billups, **Nana Boateng**, Malcolm Smith, and Peter Houghton. 

Memphis, TN

 2016.


### Gastrostomy Complications in Pediatric Cancer Patients: A Retrospective Single-Institution Review, Pediatric Blood & Cancer 62(7):S184-S185.

Fernandez Israel, John A. Sandoval, Reagan M. Jones, **Nana Boateng**, Jianrong Wu, Bhaskar N. Rao,. Andrew M. Davidoff, Stephen A. 


Memphis, TN

2015.


### Numerical Partial Differential Solution of The Black-Scholes Equation, Lambert Academic.Publishing.

**Nana Boateng**

Memphis, TN

2013




Technical  Experience {data-icon=cogs}
--------------------------------------------------------------------------------

### Machine Learning and Statistical Techniques


- Deep Learning and Distributed Deep Learning .
- Bayesian Inference (A/B Testing), Causal Bayesian Networks.
- Predictive Analytics and Time Series Modeling.
- Survival Analysis.
- Unsupervised learning: Clustering Algorithms, Dimensionality Reduction (PCA, t-SNE, UMAP).
- Reinforcement learning.
- Recommender systems and network analysis.
- Non-parametric Regression and Methods.
- Computational Modeling and Biostatistics in Gene Expression Data.
- Sentiment Analysis (structured and unstructured data sets).
- Sample Size Estimation and Power Analysis.
- Analysis of Count Data.
- Optimization techniques (linear / nonlinear programming, dynamic / stochastic programming).
- Quantitative finance (Monte Carlo simulation, risk quantification, portfolio optimization, economic scenario generation).
- Parallel, GPU and Cloud computing.
- Spatial Analytics and Spatial Data Visualization.






```{r eval=FALSE, include=FALSE}
if(PDF_EXPORT){
  cat("
  
Links {data-icon=link}
--------------------------------------------------------------------------------

<br>


")
  
  walk2(links, 1:length(links), function(link, index){
    print(glue('{index}. {link}'))
  })
}
```

